[package]
name = "file_graph-rs"
version = "0.1.0"
edition = "2021"
authors = ["vablings"]
description = "A tiny crate to generate a tree like structure starting from a folder and branching inwards"
repository = "https://github.com/vablings/file_graph-rs"
license-file = "LICENSE"

